OTD-6206 Deploy NW to auth staging environment
File "<string>", line 1, in <module>
File "/nw/src/essence-auth-v2.0/setup.py", line 7
print sys.executable
     ^
SyntaxError: Missing parentheses in call to 'print'